# Generated by Django 4.1.7 on 2023-03-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='daysToImplement',
        ),
        migrations.RemoveField(
            model_name='task',
            name='language',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taken',
        ),
    ]
