# Generated by Django 5.0.1 on 2024-01-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_task_description_alter_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
