# Generated by Django 4.1.7 on 2023-03-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('employmentDate', models.DateField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('wage', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
